"""Initial schema.

Built from the SQLAlchemy metadata rather than hand-written DDL. Eighteen tables and nine
enums land together and there is nothing to diff against, so generating from the models
removes the one real risk here: migration DDL drifting from the model definitions.

Every migration after this one is a normal autogenerated diff (`make revision m="..."`).

Revision ID: 0001
Revises:
"""

from collections.abc import Sequence

import app.models  # noqa: F401  populates Base.metadata
from alembic import op
from app.db import Base

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
