"""Image pipeline metadata.

Autogenerated, then corrected by hand for two Alembic/PostgreSQL behaviours that bite here:

* `op.add_column` with a `sa.Enum` does **not** emit `CREATE TYPE`, so the column creation
  fails against a real database. The types are created explicitly first, and the columns then
  reference them with `create_type=False`.
* The generated downgrade dropped the columns but left the types behind, so a
  downgrade-then-upgrade cycle failed with "type already exists". It drops them now.

Revision ID: 0002
Revises: 0001
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

capture_source = postgresql.ENUM(
    "upload", "webcam", "picamera", "import", name="capture_source", create_type=False
)
quality_verdict = postgresql.ENUM(
    "ok", "review", "reject", name="quality_verdict", create_type=False
)


def upgrade() -> None:
    bind = op.get_bind()
    capture_source.create(bind, checkfirst=True)
    quality_verdict.create(bind, checkfirst=True)

    op.add_column("images", sa.Column("source", capture_source, nullable=True))
    op.add_column("images", sa.Column("px_per_mm", sa.Numeric(precision=8, scale=3), nullable=True))
    op.add_column(
        "images", sa.Column("detection_confidence", sa.Numeric(precision=5, scale=4), nullable=True)
    )
    op.add_column("images", sa.Column("corners", postgresql.JSONB(), nullable=True))
    op.add_column("images", sa.Column("rotation_applied", sa.Integer(), nullable=True))
    op.add_column("images", sa.Column("quality_verdict", quality_verdict, nullable=True))
    op.add_column("images", sa.Column("quality", postgresql.JSONB(), nullable=True))
    op.add_column("images", sa.Column("error", sa.Text(), nullable=True))


def downgrade() -> None:
    for column in (
        "error",
        "quality",
        "quality_verdict",
        "rotation_applied",
        "corners",
        "detection_confidence",
        "px_per_mm",
        "source",
    ):
        op.drop_column("images", column)

    bind = op.get_bind()
    quality_verdict.drop(bind, checkfirst=True)
    capture_source.drop(bind, checkfirst=True)
