"""Record which strategy located the card.

A manually corrected card should be visibly distinct from an automatically detected one,
both in the capture strip and to Phase 3, which should not treat hand-placed corners as a
weak signal.

Revision ID: 0004
Revises: 0003
Create Date: 2026-08-24 01:37:16.894031
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('detection_method', sa.String(length=48), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'detection_method')
    # ### end Alembic commands ###
