"""Mark captures that contain no card.

Some captures are deliberate negative examples — a selfie, an empty frame. Scoring a
non-detection on those as a detector failure makes the benchmark lie about how well it
is doing, so they are labelled rather than quietly excluded.

Revision ID: 0005
Revises: 0004
Create Date: 2026-08-24 02:26:16.525816
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_items', sa.Column('contains_card', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_items', 'contains_card')
    # ### end Alembic commands ###
