"""Perceptual hash of each card's official art.

Stored on the card rather than mirroring the images: hashes for the whole English catalogue
are under a megabyte, where the art would be roughly 2GB. High-resolution art is fetched on
demand for the few candidates that reach registration.

Revision ID: 0006
Revises: 0005
Create Date: 2026-08-25 03:05:11.535459
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('art_phash', sa.BigInteger(), nullable=True))
    op.add_column('cards', sa.Column('art_hashed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('cards', sa.Column('art_hash_error', sa.Text(), nullable=True))
    op.create_index(op.f('ix_cards_art_phash'), 'cards', ['art_phash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cards_art_phash'), table_name='cards')
    op.drop_column('cards', 'art_hash_error')
    op.drop_column('cards', 'art_hashed_at')
    op.drop_column('cards', 'art_phash')
    # ### end Alembic commands ###
