"""Spatial grid hash for card art.

A single 64-bit perceptual hash averages the whole card and loses layout, which is most of
what distinguishes one card from another. Hashing each cell of a 4x4 grid keeps it: 16
hashes, 1024 bits, 128 bytes per card and about 3MB for the English catalogue.

Revision ID: 0008
Revises: 0007
Create Date: 2026-08-31 14:05:46.252353
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0008"
down_revision: str | None = "0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('art_grid_hash', sa.LargeBinary(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'art_grid_hash')
    # ### end Alembic commands ###
